export const SPREADSHEET_TEMPLATES = {
  blank: [
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }],
  ],

  balance_sheet: [
    [{ value: 'BALANCE SHEET' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Company Name:' }, { value: '' }, { value: 'Date:' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'ASSETS' }, { value: 'Amount (₱)' }, { value: 'LIABILITIES & EQUITY' }, { value: 'Amount (₱)' }],
    [{ value: 'Current Assets' }, { value: '' }, { value: 'Current Liabilities' }, { value: '' }],
    [{ value: '  Cash' }, { value: '' }, { value: '  Accounts Payable' }, { value: '' }],
    [{ value: '  Accounts Receivable' }, { value: '' }, { value: '  Notes Payable (short-term)' }, { value: '' }],
    [{ value: '  Inventory' }, { value: '' }, { value: '  Accrued Liabilities' }, { value: '' }],
    [{ value: '  Prepaid Expenses' }, { value: '' }, { value: 'Total Current Liabilities' }, { value: '' }],
    [{ value: 'Total Current Assets' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: 'Long-term Liabilities' }, { value: '' }],
    [{ value: 'Non-Current Assets' }, { value: '' }, { value: '  Bank Loan' }, { value: '' }],
    [{ value: '  Property & Equipment' }, { value: '' }, { value: '  Bonds Payable' }, { value: '' }],
    [{ value: '  Less: Depreciation' }, { value: '' }, { value: 'Total Long-term Liabilities' }, { value: '' }],
    [{ value: '  Investments' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Total Non-Current Assets' }, { value: '' }, { value: "Owner's Equity" }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '  Capital' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '  Retained Earnings' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: "Total Owner's Equity" }, { value: '' }],
    [{ value: 'TOTAL ASSETS' }, { value: '' }, { value: 'TOTAL LIAB. & EQUITY' }, { value: '' }],
  ],

  income_statement: [
    [{ value: 'INCOME STATEMENT' }, { value: '' }],
    [{ value: 'Company:' }, { value: '' }],
    [{ value: 'Period:' }, { value: '' }],
    [{ value: '' }, { value: '' }],
    [{ value: 'REVENUES' }, { value: 'Amount (₱)' }],
    [{ value: '  Sales Revenue' }, { value: '' }],
    [{ value: '  Service Revenue' }, { value: '' }],
    [{ value: '  Other Income' }, { value: '' }],
    [{ value: 'Total Revenue' }, { value: '' }],
    [{ value: '' }, { value: '' }],
    [{ value: 'COST OF GOODS SOLD (COGS)' }, { value: '' }],
    [{ value: '  Beginning Inventory' }, { value: '' }],
    [{ value: '  Add: Purchases' }, { value: '' }],
    [{ value: '  Less: Ending Inventory' }, { value: '' }],
    [{ value: 'Total COGS' }, { value: '' }],
    [{ value: 'GROSS PROFIT' }, { value: '' }],
    [{ value: '' }, { value: '' }],
    [{ value: 'OPERATING EXPENSES' }, { value: '' }],
    [{ value: '  Salaries Expense' }, { value: '' }],
    [{ value: '  Rent Expense' }, { value: '' }],
    [{ value: '  Utilities Expense' }, { value: '' }],
    [{ value: '  Depreciation Expense' }, { value: '' }],
    [{ value: '  Other Expenses' }, { value: '' }],
    [{ value: 'Total Operating Expenses' }, { value: '' }],
    [{ value: 'OPERATING INCOME' }, { value: '' }],
    [{ value: '' }, { value: '' }],
    [{ value: '  Income Tax Expense' }, { value: '' }],
    [{ value: 'NET INCOME / (LOSS)' }, { value: '' }],
  ],

  cash_flow: [
    [{ value: 'STATEMENT OF CASH FLOWS' }, { value: '' }],
    [{ value: 'Company:' }, { value: '' }],
    [{ value: 'Period:' }, { value: '' }],
    [{ value: '' }, { value: '' }],
    [{ value: 'OPERATING ACTIVITIES' }, { value: 'Amount (₱)' }],
    [{ value: '  Net Income' }, { value: '' }],
    [{ value: '  Add: Depreciation' }, { value: '' }],
    [{ value: '  Decrease/(Increase) in Accounts Receivable' }, { value: '' }],
    [{ value: '  Decrease/(Increase) in Inventory' }, { value: '' }],
    [{ value: '  Increase/(Decrease) in Accounts Payable' }, { value: '' }],
    [{ value: 'Net Cash from Operating Activities' }, { value: '' }],
    [{ value: '' }, { value: '' }],
    [{ value: 'INVESTING ACTIVITIES' }, { value: '' }],
    [{ value: '  Purchase of Equipment' }, { value: '' }],
    [{ value: '  Sale of Investments' }, { value: '' }],
    [{ value: 'Net Cash from Investing Activities' }, { value: '' }],
    [{ value: '' }, { value: '' }],
    [{ value: 'FINANCING ACTIVITIES' }, { value: '' }],
    [{ value: '  Proceeds from Loans' }, { value: '' }],
    [{ value: '  Repayment of Loans' }, { value: '' }],
    [{ value: "  Owner's Withdrawals" }, { value: '' }],
    [{ value: 'Net Cash from Financing Activities' }, { value: '' }],
    [{ value: '' }, { value: '' }],
    [{ value: 'Net Increase/(Decrease) in Cash' }, { value: '' }],
    [{ value: 'Beginning Cash Balance' }, { value: '' }],
    [{ value: 'ENDING CASH BALANCE' }, { value: '' }],
  ],

  t_account: [
    [{ value: 'ACCOUNT NAME:' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '── DEBIT ──' }, { value: 'Amount' }, { value: '' }, { value: '── CREDIT ──' }, { value: 'Amount' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Total Debits' }, { value: '' }, { value: '' }, { value: 'Total Credits' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Balance (DR - CR)' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
  ],

  trial_balance: [
    [{ value: 'TRIAL BALANCE' }, { value: '' }, { value: '' }],
    [{ value: 'Company:' }, { value: '' }, { value: '' }],
    [{ value: 'Date:' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Account Title' }, { value: 'Debit (₱)' }, { value: 'Credit (₱)' }],
    [{ value: 'Cash' }, { value: '' }, { value: '' }],
    [{ value: 'Accounts Receivable' }, { value: '' }, { value: '' }],
    [{ value: 'Inventory' }, { value: '' }, { value: '' }],
    [{ value: 'Equipment' }, { value: '' }, { value: '' }],
    [{ value: 'Accounts Payable' }, { value: '' }, { value: '' }],
    [{ value: 'Capital' }, { value: '' }, { value: '' }],
    [{ value: 'Sales Revenue' }, { value: '' }, { value: '' }],
    [{ value: 'Salaries Expense' }, { value: '' }, { value: '' }],
    [{ value: 'Rent Expense' }, { value: '' }, { value: '' }],
    [{ value: 'Utilities Expense' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }],
    [{ value: 'TOTALS' }, { value: '' }, { value: '' }],
  ],

  journal_entries: [
    [{ value: 'GENERAL JOURNAL' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Company:' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Date' }, { value: 'Account Title & Explanation' }, { value: 'Ref.' }, { value: 'Debit (₱)' }, { value: 'Credit (₱)' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: 'TOTALS' }, { value: '' }, { value: '' }],
  ],

  budget: [
    [{ value: 'BUDGET PLAN' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Period:' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Category' }, { value: 'Budgeted (₱)' }, { value: 'Actual (₱)' }, { value: 'Variance (₱)' }],
    [{ value: 'INCOME' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '  Salary / Revenue' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '  Other Income' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Total Income' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'EXPENSES' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '  Rent / Mortgage' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '  Food & Groceries' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '  Transportation' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '  Utilities' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '  Savings' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '  Other Expenses' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Total Expenses' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'NET SURPLUS / (DEFICIT)' }, { value: '' }, { value: '' }, { value: '' }],
  ],

  inventory: [
    [{ value: 'INVENTORY LEDGER' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Product:' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Date' }, { value: 'Description' }, { value: 'Unit Cost' }, { value: 'Units In' }, { value: 'Units Out' }, { value: 'Units Balance' }, { value: 'Total Value' }],
    [{ value: '' }, { value: 'Beginning Balance' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
  ],

  data_table: [
    [{ value: 'Category' }, { value: 'Q1' }, { value: 'Q2' }, { value: 'Q3' }, { value: 'Q4' }, { value: 'Total' }],
    [{ value: 'Item A' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Item B' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Item C' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Item D' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
    [{ value: 'Total' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }, { value: '' }],
  ],
};
